FROM node:latest
# RUN npm install -g create-vite & \
#     create-vite ytb-dwnldr-ui --template react
WORKDIR /home/ytb-dwnldr-ui/
# RUN npm install
# RUN npm install axios react-router-dom bootstrap lottie-react
CMD ["npm", "run", "dev"]