FROM node:latest
RUN npm install -g create-vite
WORKDIR /home/ytb-dwnldr-ui/
CMD ["bash", "-c", "npm install && npm run dev"]
# For testing and Debugging
# CMD ["tail", "-f", "/dev/null"]

# In order to Initialize new project 
# npm init vite@latest ytb-dwnldr-ui -- --template react --yes
# npm install axios react-router-dom bootstrap lottie-react
# npm install
# create-vite ytb-dwnldr-ui --template react